"""Render docs/EVALUATION.md from the JSON artifacts, so every number in the docs traces to a file."""

from __future__ import annotations

import json
from pathlib import Path

from payguard.models.registry import Registry


def _load(path: Path) -> dict | None:
    return json.loads(path.read_text()) if path.exists() else None


def _pct(x, d=1) -> str:
    return "n/a" if x is None else f"{100 * x:.{d}f}%"


def _money(x) -> str:
    return "n/a" if x is None else f"${x:,.0f}"


def render(artifacts: Path) -> str:
    reg = Registry(artifacts / "models")
    version = reg.read()["champion"]
    meta = json.loads((artifacts / "models" / version / "metadata.json").read_text())
    r = meta["report"]
    rep = artifacts / "reports"
    L: list[str] = []
    w = L.append

    w("# Evaluation\n")
    w(f"_Generated by `python -m payguard.report` from `artifacts/`. Champion model: `{version}`._\n")
    w("## Data and protocol\n")
    w(f"- Source: {meta['data']['source']} (real card-not-present transactions, sha256-verified).")
    w(f"- Out-of-time splits: train {meta['train_window']}, validation {meta['valid_window']} (early stopping, "
      f"calibration, policy, drift reference), **test {meta['test_window']}**, used once for these numbers.")
    w(f"- Training negatives downsampled to {meta['neg_downsample']:.0%} to fit an 8 GB dev machine; isotonic "
      "calibration on the untouched validation month restores true probabilities.")
    w(f"- LightGBM, {meta['n_features']} features, {meta['best_iteration']} trees, trained in {meta['train_seconds']:.0f}s "
      "(including ablations).\n")

    w("## Model quality (test month)\n")
    w("| Metric | Raw score | Calibrated |")
    w("|---|---|---|")
    raw, cal = r["test"]["raw"], r["test"]["calibrated"]
    for k, label in [("roc_auc", "ROC-AUC"), ("pr_auc", "PR-AUC"), ("recall_at_1pct_fpr", "Recall @ 1% FPR"),
                     ("recall_at_5pct_fpr", "Recall @ 5% FPR"), ("brier", "Brier"), ("ece", "Expected calibration error")]:
        fmt = (lambda v: f"{v:.4f}")
        w(f"| {label} | {fmt(raw[k])} | {fmt(cal[k])} |")
    w(f"\nBase fraud rate in the test month: {_pct(raw['base_rate'], 2)}. Validation-month PR-AUC "
      f"{r['valid']['calibrated']['pr_auc']:.3f} vs test {cal['pr_auc']:.3f}: the gap is one month of drift.")
    w(f"Isotonic calibration cuts expected calibration error {raw['ece'] / max(cal['ece'], 1e-9):.0f}x but costs "
      f"{raw['pr_auc'] - cal['pr_auc']:.3f} PR-AUC, because its step function ties scores. That is the price of "
      "probabilities meaningful enough for `p x amount` decisions.\n")

    w("## Decisions and money (test month)\n")
    p = r["policy"]
    w(f"Policy (fitted on validation): decline if p >= {p['decline_threshold']:.3f} (target decline precision "
      f"{p['decline_target_precision']:.0%}); review if p x amount >= ${p['review_cost']:.2f} "
      f"(base review cost ${p['base_review_cost']:.0f}, raised to fit {p['review_capacity']:.0%} analyst capacity).\n")
    w("| Strategy | Review rate | Decline rate | Fraud $ stopped | Decline precision | Review cost | Net savings |")
    w("|---|---|---|---|---|---|---|")
    names = {"approve_all": "Approve everything", "rules_as_written": "Hand-written rules only",
             "model_only": "Model + policy", "model_plus_all_rules": "Model + all rules enforced",
             "model_plus_enforced_rules": "**Model + enforced rules (shipped)**"}
    for k, label in names.items():
        d = r["decisions_test"].get(k)
        if d:
            w(f"| {label} | {_pct(d['review_rate'])} | {_pct(d['decline_rate'])} | {_pct(d['fraud_recall_amount'])} "
              f"of {_money(d['fraud_loss_total'])} | {_pct(d['decline_precision'])} | {_money(d['review_cost'])} | "
              f"{_money(d['net_savings'])} |")
    w("\nAssumptions: analysts confirm fraud they review (best case); a false decline costs 10% of the amount.\n")

    if "rules_valid" in r:
        w("## Rule hygiene (validation month)\n")
        w("Marginal = hits the model would have approved, i.e. what the rule adds on top of the model.\n")
        w("| Rule | Mode | Hit rate | Precision | Marginal hits | Marginal precision | Marginal fraud $ | Marginal review cost |")
        w("|---|---|---|---|---|---|---|---|")
        for rid, s in r["rules_valid"].items():
            w(f"| `{rid}` | {s['mode']} | {_pct(s['hit_rate'], 2)} | {_pct(s['precision'])} | {s['marginal_hits']:,} | "
              f"{_pct(s['marginal_precision'])} | {_money(s['marginal_fraud_amount'])} | {_money(s['marginal_review_cost'])} |")
        w("")

    if "ablations_test" in r:
        w("## Ablations (test month, raw scores)\n")
        w("| Feature set | ROC-AUC | PR-AUC | Recall @ 1% FPR |")
        w("|---|---|---|---|")
        labels = {"full": "All features", "no_streaming": "Without streaming features",
                  "no_vendor_signals": "Without processor signals (request + streaming)",
                  "request_only": "Request fields only"}
        for k, label in labels.items():
            a = r["ablations_test"].get(k)
            if a:
                w(f"| {label} | {a['roc_auc']:.4f} | {a['pr_auc']:.4f} | {_pct(a['recall_at_1pct_fpr'])} |")
        ab = r["ablations_test"]
        if all(k in ab for k in ("full", "no_streaming", "no_vendor_signals", "request_only")):
            w(f"\nReading this honestly: on top of the processor's own signals the streaming features add only "
              f"{ab['full']['roc_auc'] - ab['no_streaming']['roc_auc']:+.4f} ROC-AUC, because Vesta's C/D columns are "
              "already velocity counts over a longer history. They matter when no such signals exist: "
              f"{ab['request_only']['roc_auc']:.3f} to {ab['no_vendor_signals']['roc_auc']:.3f} ROC-AUC and "
              f"{ab['request_only']['pr_auc']:.3f} to {ab['no_vendor_signals']['pr_auc']:.3f} PR-AUC over request fields "
              "alone.")
        w("")

    w("## Slices (test month)\n")
    w("| Slice | n | Fraud rate | ROC-AUC | PR-AUC |")
    w("|---|---|---|---|---|")
    for dim, vals in r["slices_test"].items():
        for v, s in vals.items():
            w(f"| {dim} = {v} | {s['n']:,} | {_pct(s['fraud_rate'])} | {s['roc_auc']:.3f} | {s['pr_auc']:.3f} |")
    worst = min(((d, v, s) for d, vals in r["slices_test"].items() for v, s in vals.items()), key=lambda x: x[2]["roc_auc"])
    w(f"\nWeakest slice: **{worst[0]} = {worst[1]}** (ROC-AUC {worst[2]['roc_auc']:.3f}, n = {worst[2]['n']:,}). "
      "It is the first target for the next model iteration. For a high-amount slice, amount-aware sample "
      "weighting is the obvious experiment, since that is where fraud dollars concentrate.\n")

    parity = _load(rep / "parity.json")
    if parity:
        w("## Training/serving parity\n")
        w(f"Features computed by the live API for {parity['rows_checked']:,} replayed test-month transactions compared "
          f"with the offline training rows: **{parity['rows_with_mismatch']} rows with any mismatch** "
          f"({_pct(parity['mismatch_rate'], 3)}).")
        if parity["features_with_mismatch"]:
            w(f"Mismatching features: {parity['features_with_mismatch']}")
        w("")

    replay = _load(rep / "replay.json")
    lts = sorted((json.loads(p.read_text()) for p in rep.glob("loadtest_*.json")),
                 key=lambda d: (d["label"], d["concurrency"])) if rep.exists() else []
    if replay or lts:
        w("## Serving performance\n")
        if replay:
            q = replay["in_process_latency_ms"]
            w(f"- In-process replay of {replay['n']:,} test-month transactions (features + model + rules + DB commit, "
              f"SQLite): p50 {q['p50']:.1f} ms, p95 {q['p95']:.1f} ms, p99 {q['p99']:.1f} ms. Decisions: {replay['decisions']}.")
        if lts:
            w("\nHTTP load test against **one** uvicorn process. The test is closed-loop: each client sends its next "
              "request when the previous one returns, so at saturation latency is roughly concurrency / throughput.\n")
            w("| Topology | Concurrency | Requests | Throughput | p50 | p95 | p99 | Errors |")
            w("|---|---|---|---|---|---|---|---|")
            for lt in lts:
                q = lt["latency_ms"]
                errors = sum(v for k, v in lt["status"].items() if str(k) != "200")
                w(f"| {lt['label']} | {lt['concurrency']} | {lt['requests']:,} | {lt['throughput_rps']} req/s | "
                  f"{q['p50']} ms | {q['p95']} ms | {q['p99']} ms | {errors} |")
        w("\nHardware: a 4-core Windows laptop with 8 GB RAM and under 1 GB free, SQLite (single writer). Not a "
          "benchmark rig. Postgres and more API processes are the scaling path.\n")

    for name in ("claude", "heuristic"):
        ag = _load(rep / f"agent_eval_{name}.json")
        if not ag:
            continue
        w(f"## Investigation agent ({name})\n")
        w(f"{ag['n_cases']} replayed cases, stratified to {_pct(ag['fraud_share_in_sample'], 0)} fraud. Tools only see "
          "labels that had arrived when the case was raised (simulated chargeback delay, mean 5 days).\n")
        w("| | Coverage (not escalated) | Accuracy on decided | Fraud precision | Fraud recall | Escalated |")
        w("|---|---|---|---|---|---|")
        for key, label in (("agent", f"Agent ({name})"), ("model_baseline", "Model only (p >= 0.5)")):
            s = ag[key]
            w(f"| {label} | {_pct(s['coverage'])} | {_pct(s['accuracy_on_decided'])} | {_pct(s['fraud_precision'])} | "
              f"{_pct(s['fraud_recall'])} | {s['escalated']} |")
        g = ag.get("grounding") or {}
        cost = (f", estimated cost ${ag['est_cost_usd_per_case']:.4f} per case" if ag["tokens"]["input"] else
                " (no LLM calls)")
        w(f"\nCitation validity {_pct(g.get('citation_valid_rate'))}, numeric grounding {_pct(g.get('grounded_rate'))}, "
          f"average {ag['avg_steps']:.1f} tool calls, p50 latency {ag['latency_s']['p50']:.2f}s{cost}.")
        od = ag.get("on_agent_decided")
        if od and od["n"]:
            w(f"On the same {od['n']} cases the agent decided: agent accuracy **{_pct(od['agent_accuracy'])}** vs model "
              f"alone {_pct(od['model_accuracy'])}. The investigation adds labels that arrived after training (related "
              "customers' confirmed chargebacks, outcomes of similar cases), which the model cannot see. "
              "With this sample size the difference is directional, not statistically conclusive.")
        if ag.get("model_accuracy_on_agent_escalations") is not None:
            w(f"The model alone is right on {_pct(ag['model_accuracy_on_agent_escalations'])} of the cases the agent "
              "escalated, so escalations concentrate on genuinely hard cases.")
        w("")

    vis = _load(artifacts / "vision" / "vision_eval.json")
    if vis:
        s = vis["summary"]
        w("## Receipt verification (computer vision)\n")
        w(f"Synthetic evaluation: {vis['n_test_per_kind']} generated receipts per kind (fictional banks; there is no public "
          "labelled set of forged transfer receipts). The ELA band was calibrated on a separate genuine validation set: "
          f"[{vis['thresholds']['ela_low']:.3f}, {vis['thresholds']['ela_high']:.3f}].\n")
        w("| Regime | Metric | Value |")
        w("|---|---|---|")
        for k, v in s["with_ledger"].items():
            w(f"| Ledger available | {k.replace('_', ' ')} | {_pct(v)} |")
        for k, v in s["forensics_only"].items():
            w(f"| Ledger unavailable (ELA only) | {k.replace('_', ' ')} | {_pct(v)} |")
        w(f"\nOCR latency per receipt on CPU: p50 {s['latency_s']['p50']:.2f}s, p95 {s['latency_s']['p95']:.2f}s.\n")

    dd = _load(rep / "drift_demo.json")
    if dd:
        w("## Drift incident drill\n")
        w("Replaying 4,000 test-month transactions normally, then with a simulated upstream bug (processor signal C13 "
          "zeroed and 30% of amounts sent in minor units):\n")
        w("| Run | Status | Score PSI | Flag rate | Drifted features |")
        w("|---|---|---|---|---|")
        for name, d in dd.items():
            w(f"| {name} | {d['status']} | {d['score_psi']} | {_pct(d['flag_rate'])} | {', '.join(d['drifted_features']) or '-'} |")
        w("")
    _crypto(artifacts, w)
    return "\n".join(L) + "\n"


def _crypto(artifacts: Path, w) -> None:
    root = artifacts / "models" / "crypto"
    if not (root / "champion.txt").exists():
        return
    d = root / (root / "champion.txt").read_text().strip()
    meta = json.loads((d / "metadata.json").read_text())["report"]
    w("## Crypto: on-chain transaction risk model (Elliptic++, real Bitcoin data)\n")
    p = meta["protocol"]
    w(f"Strict-inductive, out-of-time: train steps {p['train_steps'][0]}-{p['train_steps'][1]}, validation "
      f"{p['valid_steps'][0]}-{p['valid_steps'][1]}, test {p['test_steps'][0]}-{p['test_steps'][1]}; a large dark "
      f"market shut down at step {p['dark_market_shutdown_step']}. Per-transaction metrics on labelled test "
      "transactions, threshold fixed on validation (max F1).\n")
    w("| Model | Illicit F1 | PR-AUC | ROC-AUC | Precision | Recall | F1 before shutdown | F1 after shutdown |")
    w("|---|---|---|---|---|---|---|---|")
    for name, v in meta["variants"].items():
        t, pre, post = v["test"], v["test_pre_shutdown"], v["test_post_shutdown"] or {}
        w(f"| {name}{' **(champion)**' if name == meta['champion']['variant'] else ''} | {t['illicit_f1']:.3f} | "
          f"{t['pr_auc']:.3f} | {t['roc_auc']:.3f} | {_pct(t['precision'])} | {_pct(t['recall'])} | "
          f"{pre['illicit_f1']:.3f} | {post.get('illicit_f1', float('nan')):.3f} |")
    champ = meta["variants"][meta["champion"]["variant"]]
    w(f"\nF1 by test step (champion): {champ['f1_by_step']}. Every model, with or without graph features, "
      "collapses after the shutdown: the illicit behaviour that replaced the market was not in the training "
      "labels. This is the case for controls that do not depend on the model (sanctions screening, entity "
      "attribution, human review) and for fast retraining on fresh labels.\n")
    cb = _load(d / "combiner.json")
    if cb:
        r, c = cb["report"], cb["combiner"]
        w("## Crypto: counterparty intelligence (point-in-time)\n")
        w(f"Events: one per labelled transaction (\"a deposit from this transaction's first input address\"), "
          f"{r['n_valid_events']:,} validation / {r['n_test_events']:,} test, {_pct(r['test_illicit_share'])} "
          f"illicit. Illicit labels become visible {r['label_delay_steps']} step(s) after the activity. Entity "
          "features use common-input-ownership clustering replayed step by step.\n")
        w(f"- Test transactions whose sending address had any history: **{_pct(r['test_coverage_address_seen_before'])}**; "
          f"whose sending *entity* (via co-inputs) had history: **{_pct(r['test_coverage_entity_seen_before'])}**.")
        w("")
        w("| Signals | PR-AUC | ROC-AUC | F1 | F1 before shutdown | F1 after shutdown |")
        w("|---|---|---|---|---|---|")
        for name, v in r["variants"].items():
            post = v["test_f1_post_shutdown"]
            w(f"| {name} | {v['test_pr_auc']:.3f} | {v['test_roc_auc']:.3f} | {v['test_f1']:.3f} | "
              f"{v['test_f1_pre_shutdown']:.3f} | {'n/a' if post is None else f'{post:.3f}'} |")
        w(f"\nServing thresholds (calibrated, fixed on validation): review at {c['review_threshold']:.3f} "
          f"(>= 50% precision), block at {c['block_threshold']:.3f} (>= 95% precision).")
        for band in ("review", "block"):
            op = r.get(f"test_at_{band}_threshold")
            if op:
                w(f"- Test at the {band} threshold: flags {_pct(op['flag_rate'])} of transactions, precision "
                  f"{_pct(op['precision'])}, recall {_pct(op['recall'])}.")
        w("")


if __name__ == "__main__":
    import sys

    from payguard.config import get_settings

    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("docs/EVALUATION.md")
    out.write_text(render(get_settings().artifacts_dir), encoding="utf-8")
    print(f"wrote {out}")
